[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = [
  "npm install",
  "npm run db:generate",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "npm run build:backend",
  "npm run build:frontend"
]

[start]
cmd = "npm start"

